name: CI

on:
  push:
    branches-ignore: [staging.tmp]
    paths:
    #- 'examples/quad_android/**'
    #- '!examples/quad_android/**.md'
    #- 'src/backend/gl/**'
    #- '!src/backend/gl/**.md'
  pull_request:
    branches-ignore: [staging.tmp]
    paths:
    #- 'examples/quad_android/**'
    #- '!examples/quad_android/**.md'
    #- 'src/backend/gl/**'
    #- '!src/backend/gl/**.md'
jobs:
  test:
      runs-on: macos-10.15
      steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          script: sh ./.github/workflows/android_test.sh
      - uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: screenshot
          path: |
            ~/screenshot.png
            ~/logcat.log
