name: CI

on:
  push:
    branches-ignore: [staging.tmp]
  pull_request:
    branches-ignore: [staging.tmp]

jobs:
  webgl_build:
    name: Web Assembly
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo build --manifest-path examples/Cargo.toml --features gl --target wasm32-unknown-unknown --bin quad
      - run: cargo install -f wasm-bindgen-cli --version 0.2.69
      - run: wasm-bindgen --out-dir target/generated --web target/wasm32-unknown-unknown/debug/quad.wasm
      - run: mv ./.github/workflows/index.html ./target/generated/
      - run: curl -O --output-dir ./target/generated/ https://github.com/grovesNL/spirv_cross/raw/master/wasm/spirv_cross_wrapper_glsl.wasm
      - run: curl -O --output-dir ./target/generated/ https://github.com/grovesNL/spirv_cross/raw/master/wasm/spirv_cross_wrapper_glsl.js
      - run: npm i puppeteer-core
      - run: ruby -run -e httpd -p 8000 ./target/generated &
      - run: node ./.github/workflows/webgl_test.js
